import { __print } from './__util.js';
import * as __std_optional from './std/optional.js';
import * as __std_array from './std/array.js';
const nums = [10, 20, 30];
const first = __std_array._ext_array__get(nums, 0);
const out = __std_optional._ext_optional__val_or(__std_array._ext_array__get(nums, 0), 0);
__print(`Out: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(out)}`);
const strings = ["Hello", "World"];
__print(`Nums: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(nums)}`);
__print(`First: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(first)}`);
__print(`Strings: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(strings)}`);
