import { __print, __range } from './__util.js';
import * as __std_string from './std/string.js';
import * as __std_array from './std/array.js';
const greeting = "Hello World";
const ch = greeting.charAt(0);
__print(`First char: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(ch)}`);
const pos = greeting.indexOf("World");
__print(`Position of World: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(pos)}`);
__print(`Length of greeting: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(greeting.length)}`);
__print(__std_string._ext_string__shout(greeting));
__print(__std_string._ext_string__whisper(greeting));
const nums = __range(1, 100, true);
__print(`original : ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(nums)}`);
__std_array._ext_array__shuffle(nums);
__print(`shuffled : ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(nums)}`);
__print(`First 5: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_string._ext_string__first_n(greeting, 5))}`);
