import { __print, __range } from './__util.js';
import * as __std_array from './std/array.js';
import * as __std_string from './std/string.js';
const greeting = "Hello World";
const ch = greeting.charAt(0);
__print(`First char: ${ch}`);
const pos = greeting.indexOf("World");
__print(`Position of World: ${pos}`);
__print(`Length of greeting: ${greeting.length}`);
__print(__std_string._ext_string__shout(greeting));
__print(__std_string._ext_string__whisper(greeting));
const nums = __range(1, 100, true);
__print(`original : ${nums}`);
__std_array._ext_array__shuffle(nums);
__print(`shuffled : ${nums}`);
__print(`First 5: ${__std_string._ext_string__first_n(greeting, 5)}`);
