import { __print } from './__util.js';
import * as __std_string from './std/string.js';
import * as __user from './__user_ext.js';
const v1 = { x: 10, y: 20 };
const v2 = { x: 5, y: 3 };
__print("v1 + v2:");
const sum = __user._ext_usr_Vector2__op_plus(v1, v2);
__print(sum);
__print("v1 - v2:");
const diff = __user._ext_usr_Vector2__op_minus(v1, v2);
__print(diff);
__print("v1 * 2:");
const scaled = __user._ext_usr_Vector2__op_mul(v1, 2);
__print(scaled);
__print("v1 / 2:");
const half = __user._ext_usr_Vector2__op_div(v1, 2);
__print(half);
__print("(v1 + v2) * 0.5:");
const result = __user._ext_usr_Vector2__op_mul(__user._ext_usr_Vector2__op_plus(v1, v2), 0.5);
__print(result);
const repeated = __std_string._ext_string__op_mul("Hello ", 3);
__print(repeated);
