import { __print } from './__util.js';
import * as __std_dict from './std/dict.js';
__print("=== Basic Operations ===");
const scores = { "Alice": 95, "Bob": 87, "Charlie": 92 };
__print(`Length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(scores))}`);
__print(`Is empty: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__is_empty(scores))}`);
__print(`Contains Alice: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__contains(scores, "Alice"))}`);
__print(`Contains David: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__contains(scores, "David"))}`);
const alice_score = __std_dict._ext_dict__get(scores, "Alice");
__print(`Alice's score: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(alice_score)}`);
const david_score = __std_dict._ext_dict__get(scores, "David");
__print(`David's score: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(david_score)}`);
__std_dict._ext_dict__set(scores, "David", 88);
__print(`After adding David, length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(scores))}`);
__print("\n=== Iteration ===");
const keys = __std_dict._ext_dict__keys(scores);
__print(`Keys: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(keys)}`);
const values = __std_dict._ext_dict__values(scores);
__print(`Values: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(values)}`);
__print("\n=== Transformation ===");
const double_score = (score) => (score * 2);
const doubled = __std_dict._ext_dict__map(scores, double_score);
__print(`Doubled scores: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(doubled)}`);
const is_high_score = (name, score) => (score >= 90);
const high_scores = __std_dict._ext_dict__filter(scores, is_high_score);
__print(`High scores (>=90): ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(high_scores)}`);
__print("\n=== Merging ===");
const extra_scores = { "Eve": 91, "Frank": 85 };
const all_scores = __std_dict._ext_dict__merge(scores, extra_scores);
__print(`Merged scores length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(all_scores))}`);
const combined = __std_dict._ext_dict__op_plus(scores, extra_scores);
__print(`Combined with + length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(combined))}`);
__print("\n=== Pick & Omit ===");
const selected = __std_dict._ext_dict__pick(all_scores, ["Alice", "Eve", "Frank"]);
__print(`Picked Alice, Eve, Frank: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(selected)}`);
const without_bob = __std_dict._ext_dict__omit(all_scores, ["Bob", "David"]);
__print(`Omitted Bob, David: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(without_bob)}`);
__print("\n=== Querying ===");
const is_top_score = (score) => (score > 93);
const top_scorer = __std_dict._ext_dict__find_key(all_scores, is_top_score);
__print(`Top scorer (>93): ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(top_scorer)}`);
const is_above_90 = (score) => (score > 90);
const has_high = __std_dict._ext_dict__any(all_scores, is_above_90);
__print(`Any score > 90: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(has_high)}`);
const is_passing = (score) => (score >= 80);
const all_passing = __std_dict._ext_dict__every(all_scores, is_passing);
__print(`All scores >= 80: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(all_passing)}`);
const count_high = (name, score) => (score >= 90);
const high_count = __std_dict._ext_dict__count(all_scores, count_high);
__print(`Count of scores >= 90: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(high_count)}`);
__print("\n=== For Each ===");
__print("Printing all scores:");
const print_score = (name, score) => {
    __print(`  ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(name)}: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(score)}`);
  return undefined;
};
__std_dict._ext_dict__for_each(all_scores, print_score);
__print("\n=== Clear & Remove ===");
const temp = { "x": 1, "y": 2, "z": 3 };
__print(`Before operations - length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(temp))}`);
const removed = __std_dict._ext_dict__remove(temp, "y");
__print(`Removed 'y': ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(removed)}, length now: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(temp))}`);
__std_dict._ext_dict__clear(temp);
__print(`After clear - length: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__len(temp))}, is empty: ${((_v) => typeof _v === 'object' && _v !== null ? JSON.stringify(_v) : _v)(__std_dict._ext_dict__is_empty(temp))}`);
